# Pokemon analysis: clustering and unsupervised learning

## Package import, dataset import and exploration

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# data
df = pd.read_csv("/home/joy/Documents/Education/Python Scripts/pokemon-data-science-project/data/pokemon_complete.csv")

In [3]:
df

,pokedex_number,name,type_1,type_2,hp,attack,defense,sp_attack,sp_defense,speed,...,shape,egg_groups,habitat,growth_rate,capture_rate,base_happiness,genus,evolution_chain_id,flavor_text,sprite_url
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,...,quadruped,monster|plant,grassland,medium-slow,45,70,Seed Pokémon,1,A strange seed was planted on its back at birt...,https://raw.githubusercontent.com/PokeAPI/spri...
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,...,quadruped,monster|plant,grassland,medium-slow,45,70,Seed Pokémon,1,"When the bulb on its back grows large, it appe...",https://raw.githubusercontent.com/PokeAPI/spri...
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,...,quadruped,monster|plant,grassland,medium-slow,45,70,Seed Pokémon,1,The plant blooms when it is absorbing solar en...,https://raw.githubusercontent.com/PokeAPI/spri...
3,4,Charmander,Fire,NaN,39,52,43,60,50,65,...,upright,monster|dragon,mountain,medium-slow,45,70,Lizard Pokémon,2,"Obviously prefers hot places. When it rains, s...",https://raw.githubusercontent.com/PokeAPI/spri...
4,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,...,upright,monster|dragon,mountain,medium-slow,45,70,Flame Pokémon,2,"When it swings its burning tail, it elevates t...",https://raw.githubusercontent.com/PokeAPI/spri...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1345,10321,Glimmora-Mega,Rock,Poison,83,90,105,150,96,101,...,ball,mineral,NaN,medium-slow,25,50,Ore Pokémon,508,"When this Pokémon detects danger, it will open...",NaN
1346,10322,Tatsugiri-Curly-Mega,Dragon,Water,68,65,90,135,125,92,...,fish,water2,NaN,medium-slow,100,50,Mimicry Pokémon,514,This is a small dragon Pokémon. It lives insid...,NaN
1347,10323,Tatsugiri-Droopy-Mega,Dragon,Water,68,65,90,135,125,92,...,fish,water2,NaN,medium-slow,100,50,Mimicry Pokémon,514,This is a small dragon Pokémon. It lives insid...,NaN
1348,10324,Tatsugiri-Stretchy-Mega,Dragon,Water,68,65,90,135,125,92,...,fish,water2,NaN,medium-slow,100,50,Mimicry Pokémon,514,This is a small dragon Pokémon. It lives insid...,NaN
1349,10325,Baxcalibur-Mega,Dragon,Ice,115,175,117,105,101,87,...,upright,dragon|mineral,NaN,slow,10,50,Ice Dragon Pokémon,527,This Pokémon blasts cryogenic air out from its...,NaN

In [4]:
print(df.columns)

Index(['pokedex_number', 'name', 'type_1', 'type_2', 'hp', 'attack', 'defense',
       'sp_attack', 'sp_defense', 'speed', 'base_stat_total', 'height_m',
       'weight_kg', 'base_experience', 'abilities', 'hidden_ability',
       'generation', 'is_legendary', 'is_mythical', 'is_baby', 'color',
       'shape', 'egg_groups', 'habitat', 'growth_rate', 'capture_rate',
       'base_happiness', 'genus', 'evolution_chain_id', 'flavor_text',
       'sprite_url'],
      dtype='str')

In [5]:
# dataset discovery
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1350 entries, 0 to 1349
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   pokedex_number      1350 non-null   int64
 1   name                1350 non-null   str
 2   type_1              1350 non-null   str
 3   type_2              765 non-null    str
 4   hp                  1350 non-null   int64
 5   attack              1350 non-null   int64
 6   defense             1350 non-null   int64
 7   sp_attack           1350 non-null   int64
 8   sp_defense          1350 non-null   int64
 9   speed               1350 non-null   int64
 10  base_stat_total     1350 non-null   int64
 11  height_m            1350 non-null   float64
 12  weight_kg           1350 non-null   float64
 13  base_experience     1302 non-null   float64
 14  abilities           1325 non-null   str
 15  hidden_ability      988 non-null    str
 16  generation          1350 non-null   str
 17  is_legendary        1350 non-null   bool
 18  is_mythical         1350 non-null   bool
 19  is_baby             1350 non-null   bool
 20  color               1350 non-null   str
 21  shape               1350 non-null   str
 22  egg_groups          1350 non-null   str
 23  habitat             520 non-null    str
 24  growth_rate         1350 non-null   str
 25  capture_rate        1350 non-null   int64
 26  base_happiness      1350 non-null   int64
 27  genus               1350 non-null   str
 28  evolution_chain_id  1350 non-null   int64
 29  flavor_text         1350 non-null   str
 30  sprite_url          1290 non-null   str
dtypes: bool(3), float64(3), int64(11), str(14)
memory usage: 299.4 KB

In [6]:
df.describe()

,pokedex_number,hp,attack,defense,sp_attack,sp_defense,speed,base_stat_total,height_m,weight_kg,base_experience,capture_rate,base_happiness,evolution_chain_id
count,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1302.000000,1350.000000,1350.000000,1350.000000
mean,2836.148148,71.671852,82.783704,76.194074,75.368148,74.095556,71.961481,452.074815,2.045259,99.171926,161.943932,89.120741,59.396296,253.156296
std,4135.531960,26.837396,32.350046,30.724283,33.989075,27.801487,30.620661,122.462374,5.325712,195.368919,82.532554,74.419310,23.239064,163.129522
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,175.000000,0.100000,0.000000,36.000000,3.000000,0.000000,1.000000
25%,338.250000,55.000000,60.000000,55.000000,50.000000,54.000000,49.000000,340.000000,0.600000,9.425000,71.000000,45.000000,50.000000,102.250000
50%,675.500000,70.000000,80.000000,70.000000,69.000000,70.000000,70.000000,475.000000,1.100000,32.700000,165.000000,55.000000,70.000000,258.000000
75%,1012.750000,85.000000,102.750000,95.000000,97.000000,90.000000,94.750000,530.000000,1.700000,85.425000,222.500000,120.000000,70.000000,392.000000
max,10325.000000,255.000000,190.000000,250.000000,216.000000,250.000000,200.000000,1125.000000,100.000000,1000.000000,608.000000,255.000000,140.000000,549.000000

In [7]:
df.shape

(1350, 31)

##

In [8]:
# select numeric vs str columns
num_columns = df[df.select_dtypes(include=['int', 'int64', np.number, 'float64']).columns]
str_columns = df[df.select_dtypes(include=['str']).columns]

# dropping the first column of num_columns since it's just the pokemon's number and has no statistical value
num_columns = num_columns.drop(["pokedex_number"], axis=1)